import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ImageCard } from "@/components/ImageCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageCard
        images={[
          "/0200BFB6-A129-4755-BA9A-0DD241DA33C8.jpg",
          "/0200BFB6-A129-4755-BA9A-0DD241DA33C8_1.jpg",
          "/0200BFB6-A129-4755-BA9A-0DD241DA33C8_2.jpg",
        ]}
      />
    </>
  );
}
