import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { HomeCard } from "@/components/HomeCard";
import { useCallback, useContext, useEffect, useState } from "react";
import { HomeListContext } from "../utils/HomeListContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { homes, getNextPage } = useContext(HomeListContext);
  const [scrolling, setScrolling] = useState(false);
  const infiniteScroll = useCallback(() => {
    if (scrolling) {
      const { scrollTop, clientHeight, scrollHeight } =
        document.documentElement;
      if (scrollTop + clientHeight >= scrollHeight) {
        getNextPage(30);
      }
      setScrolling(false);
    }
  }, [getNextPage, setScrolling, scrolling]);

  const scrollHandler = useCallback(() => setScrolling(true), [setScrolling]);
  useEffect(() => {
    const interval = setInterval(() => {
      infiniteScroll();
    }, 500);
    window.addEventListener("scroll", scrollHandler);
    return () => {
      window.removeEventListener("scroll", scrollHandler);
      clearInterval(interval);
    };
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.flexGrid}>
        {homes.map((home, i) => (
          <HomeCard home={home} key={i} />
        ))}
      </div>
    </>
  );
}
